# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_auto_20191003_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
