# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_course_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructions',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
