# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-05 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_course_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
