# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
