# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-30 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_auto_20191003_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_provider',
            field=models.CharField(default='YouTube', max_length=50),
        ),
    ]
