# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-04 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0010_video_content_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content_provider',
        ),
    ]
