# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20191003_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='video_app.Video'),
        ),
    ]
